import type { DownstreamModel, TargetModel, TaskCategory } from "./types";

export const TASK_CATEGORIES: Array<{ key: TaskCategory; name: string; desc: string }> = [
  { key: "none", name: "不下发生成", desc: "只锻造大脑模型自己的 System Prompt" },
  { key: "text2img", name: "文生图", desc: "输出主体、场景、风格、镜头与负面词" },
  { key: "img2img", name: "图生图", desc: "先解析参考图，再输出保留与修改策略" },
  { key: "edit", name: "图像编辑", desc: "把自然语言编辑需求拆成可执行操作序列" },
  { key: "text2video", name: "文生视频", desc: "输出动作、运镜、节奏、时长与声音提示" },
  { key: "img2video", name: "图生视频", desc: "基于首帧规划主体运动、镜头运动与尾帧" },
];

export const TARGET_MODELS: TargetModel[] = [
  { value: "gpt-5.5-pro", label: "GPT-5.5 Pro", vendor: "OpenAI", vision: true, reasoning: true, tag: "旗舰", family: "closed" },
  { value: "gpt-5.5", label: "GPT-5.5", vendor: "OpenAI", vision: false, reasoning: true, tag: "旗舰", family: "closed" },
  { value: "gpt-5.4", label: "GPT-5.4", vendor: "OpenAI", vision: false, reasoning: true, family: "closed" },
  { value: "gpt-4o", label: "GPT-4o", vendor: "OpenAI", vision: true, family: "closed" },
  { value: "claude-opus-4.8", label: "Claude Opus 4.8", vendor: "Anthropic", vision: true, reasoning: true, tag: "旗舰", family: "closed" },
  { value: "claude-sonnet-5", label: "Claude Sonnet 5", vendor: "Anthropic", vision: true, reasoning: true, tag: "主力", family: "closed" },
  { value: "claude-sonnet-4.6", label: "Claude Sonnet 4.6", vendor: "Anthropic", vision: false, family: "closed" },
  { value: "claude-haiku-4.5", label: "Claude Haiku 4.5", vendor: "Anthropic", vision: false, tag: "轻量", family: "closed" },
  { value: "gemini-3.5-flash", label: "Gemini 3.5 Flash", vendor: "Google", vision: true, tag: "快·多模态", family: "closed" },
  { value: "gemini-3.1-pro", label: "Gemini 3.1 Pro", vendor: "Google", vision: true, reasoning: true, family: "closed" },
  { value: "gemini-2.5-pro", label: "Gemini 2.5 Pro", vendor: "Google", vision: false, reasoning: true, family: "closed" },
  { value: "grok-4.3", label: "Grok 4.3", vendor: "xAI", vision: true, family: "closed" },
  { value: "doubao-seed-2.1-pro", label: "豆包 Seed 2.1 Pro", vendor: "ByteDance", vision: true, reasoning: true, tag: "国产旗舰", family: "closed" },
  { value: "doubao-seed-evolving", label: "豆包 Seed Evolving", vendor: "ByteDance", vision: true, reasoning: true, family: "closed" },
  { value: "deepseek-v4-pro", label: "DeepSeek V4 Pro", vendor: "DeepSeek", vision: false, reasoning: true, tag: "深度推理", family: "closed" },
  { value: "qwen3.7-max", label: "Qwen 3.7 Max", vendor: "Alibaba", vision: false, reasoning: true, tag: "国产旗舰", family: "closed" },
  { value: "qwen3.7-plus", label: "Qwen 3.7 Plus", vendor: "Alibaba", vision: true, tag: "性价比", family: "closed" },
  { value: "glm-5v-turbo", label: "GLM-5V Turbo", vendor: "Zhipu", vision: true, reasoning: true, tag: "视觉·低价", family: "closed" },
  { value: "glm-5.2", label: "GLM-5.2", vendor: "Zhipu", vision: false, reasoning: true, family: "closed" },
  { value: "minimax-m2.7", label: "MiniMax M2.7", vendor: "MiniMax", vision: false, family: "closed" },
  { value: "qwen3.5-9b", label: "Qwen3.5-9B", vendor: "Alibaba", vision: false, reasoning: true, tag: "开源·轻量", family: "open" },
  { value: "qwen3.5-27b", label: "Qwen3.5-27B", vendor: "Alibaba", vision: false, reasoning: true, tag: "开源·主力", family: "open" },
  { value: "qwen3.6-35b", label: "Qwen3.6-35B", vendor: "Alibaba", vision: false, reasoning: true, tag: "开源·Dense", family: "open" },
  { value: "qwen3.6-35b-a3b", label: "Qwen3.6-35B-A3B", vendor: "Alibaba", vision: false, reasoning: true, tag: "开源 MoE", family: "open" },
  { value: "qwen3-vl-72b", label: "Qwen3-VL-72B", vendor: "Alibaba", vision: true, tag: "开源视觉", family: "open" },
  { value: "qwen2.5-vl-72b", label: "Qwen2.5-VL-72B", vendor: "Alibaba", vision: true, family: "open" },
  { value: "llama-4-maverick", label: "Llama 4 Maverick", vendor: "Meta", vision: true, tag: "开源旗舰", family: "open" },
  { value: "llama-4-scout", label: "Llama 4 Scout", vendor: "Meta", vision: true, family: "open" },
  { value: "deepseek-v3.2", label: "DeepSeek V3.2", vendor: "DeepSeek", vision: false, reasoning: true, tag: "开源", family: "open" },
  { value: "deepseek-r1", label: "DeepSeek R1", vendor: "DeepSeek", vision: false, reasoning: true, tag: "开源推理", family: "open" },
  { value: "glm-4.5-air", label: "GLM-4.5-Air", vendor: "Zhipu", vision: false, reasoning: true, tag: "开源", family: "open" },
  { value: "mistral-small-3.5", label: "Mistral Small 3.5", vendor: "Mistral", vision: false, family: "open" },
  { value: "phi-4", label: "Phi-4", vendor: "Microsoft", vision: false, tag: "小模型", family: "open" },
  { value: "internvl3-78b", label: "InternVL3-78B", vendor: "Shanghai AI Lab", vision: true, tag: "开源视觉", family: "open" },
];

export const DOWNSTREAM_MODELS: DownstreamModel[] = [
  { value: "gpt-image-2", label: "GPT-Image 2", category: "text2img", vendor: "OpenAI", tag: "高质量", family: "closed" },
  { value: "nano-banana-pro", label: "Nano Banana Pro (Gemini Pro Image)", category: "text2img", vendor: "Google", tag: "优质", family: "closed" },
  { value: "nano-banana2", label: "Nano Banana V2 (Gemini 3.1 Flash)", category: "text2img", vendor: "Google", tag: "性价比", family: "closed" },
  { value: "seedream-4", label: "即梦 Seedream 4.0", category: "text2img", vendor: "ByteDance", family: "closed" },
  { value: "flux-1.1-pro", label: "Flux 1.1 Pro", category: "text2img", vendor: "Black Forest", tag: "写实", family: "closed" },
  { value: "midjourney-v7", label: "Midjourney V7", category: "text2img", vendor: "Midjourney", tag: "艺术", family: "closed" },
  { value: "ideogram-3", label: "Ideogram 3", category: "text2img", vendor: "Ideogram", tag: "文字准", family: "closed" },
  { value: "recraft-v3", label: "Recraft V3", category: "text2img", vendor: "Recraft", tag: "矢量/UI", family: "closed" },
  { value: "dall-e-3", label: "DALL-E 3", category: "text2img", vendor: "OpenAI", family: "closed" },
  { value: "flux-1-dev", label: "Flux.1 Dev", category: "text2img", vendor: "Black Forest", tag: "开源", family: "open" },
  { value: "flux-1-schnell", label: "Flux.1 Schnell", category: "text2img", vendor: "Black Forest", tag: "开源·快", family: "open" },
  { value: "f2k", label: "F2K (Flux 继任)", category: "text2img", vendor: "开源社区", tag: "开源·新星", family: "open" },
  { value: "krea-2", label: "Krea 2", category: "text2img", vendor: "Krea AI", tag: "开源实时", family: "open" },
  { value: "qwen-image", label: "Qwen-Image", category: "text2img", vendor: "Alibaba", tag: "开源中文", family: "open" },
  { value: "z-image", label: "Z-Image", category: "text2img", vendor: "智象 / 开源", tag: "开源", family: "open" },
  { value: "z-image-turbo", label: "Z-Image-Turbo", category: "text2img", vendor: "智象 / 开源", tag: "开源·极速", family: "open" },
  { value: "sd-3.5-large", label: "Stable Diffusion 3.5 Large", category: "text2img", vendor: "Stability", tag: "开源", family: "open" },
  { value: "sdxl-1.0", label: "SDXL 1.0", category: "text2img", vendor: "Stability", tag: "开源经典", family: "open" },
  { value: "hunyuan-dit", label: "Hunyuan-DiT", category: "text2img", vendor: "Tencent", tag: "开源中文", family: "open" },
  { value: "kolors", label: "可图 Kolors", category: "text2img", vendor: "Kuaishou", tag: "开源中文", family: "open" },
  { value: "wanxiang-2.2-t2i", label: "万相 2.2 文生图", category: "text2img", vendor: "Alibaba", tag: "开源", family: "open" },
  { value: "gpt-image-2-i2i", label: "GPT-Image 2 图生图", category: "img2img", vendor: "OpenAI", family: "closed" },
  { value: "nano-banana-pro-i2i", label: "Nano Banana Pro 图生图", category: "img2img", vendor: "Google", family: "closed" },
  { value: "seedream-4-i2i", label: "即梦 Seedream 4.0 图生图", category: "img2img", vendor: "ByteDance", family: "closed" },
  { value: "midjourney-v7-i2i", label: "Midjourney V7 图生图", category: "img2img", vendor: "Midjourney", family: "closed" },
  { value: "flux-kontext-i2i", label: "Flux Kontext 图生图", category: "img2img", vendor: "Black Forest", tag: "开源", family: "open" },
  { value: "sd-3.5-i2i", label: "Stable Diffusion 3.5 图生图", category: "img2img", vendor: "Stability", family: "open" },
  { value: "qwen-image-i2i", label: "Qwen-Image 图生图", category: "img2img", vendor: "Alibaba", tag: "开源", family: "open" },
  { value: "qwen-image-edit-i2i", label: "Qwen-Image-Edit 图生图", category: "img2img", vendor: "Alibaba", tag: "开源改图", family: "open" },
  { value: "nano-banana-pro-edit", label: "Nano Banana Pro 图像编辑", category: "edit", vendor: "Google", tag: "指令改图", family: "closed" },
  { value: "gpt-image-2-edit", label: "GPT-Image 2 图像编辑", category: "edit", vendor: "OpenAI", family: "closed" },
  { value: "flux-kontext", label: "Flux Kontext 图像编辑", category: "edit", vendor: "Black Forest", tag: "指令改图", family: "closed" },
  { value: "bria-eraser", label: "BRIA 橡皮擦除", category: "edit", vendor: "BRIA", tag: "去物", family: "closed" },
  { value: "flux-outpaint", label: "Flux 扩图 (Outpaint)", category: "edit", vendor: "Black Forest", tag: "扩图", family: "closed" },
  { value: "qwen-image-edit-open", label: "Qwen-Image-Edit 图像编辑", category: "edit", vendor: "Alibaba", tag: "开源指令改图", family: "open" },
  { value: "firered-edit", label: "FireRed Edit", category: "edit", vendor: "FireRed / 开源", tag: "开源人像编辑", family: "open" },
  { value: "flux-kontext-dev", label: "Flux Kontext Dev (开源)", category: "edit", vendor: "Black Forest", tag: "开源", family: "open" },
  { value: "inpaint-anything-sam2", label: "Inpaint Anything (SAM2)", category: "edit", vendor: "Meta", tag: "开源·去物", family: "open" },
  { value: "diffbir", label: "DiffBIR 修复", category: "edit", vendor: "开源", tag: "修复/超分", family: "open" },
  { value: "seedance-2-pro-t2v", label: "Seedance 2.0 Pro 文生视频", category: "text2video", vendor: "ByteDance", tag: "旗舰", family: "closed" },
  { value: "seedance-2-fast-t2v", label: "Seedance 2.0 Fast 文生视频", category: "text2video", vendor: "ByteDance", tag: "高清·快", family: "closed" },
  { value: "seedance-2-mini-t2v", label: "Seedance 2.0 Mini 文生视频", category: "text2video", vendor: "ByteDance", tag: "极速·低价", family: "closed" },
  { value: "veo-3", label: "Veo 3 文生视频", category: "text2video", vendor: "Google", tag: "高品质·有声", family: "closed" },
  { value: "sora-2", label: "Sora 2 文生视频", category: "text2video", vendor: "OpenAI", family: "closed" },
  { value: "kling-2-t2v", label: "可灵 Kling 2 文生视频", category: "text2video", vendor: "Kuaishou", family: "closed" },
  { value: "runway-gen-3-alpha", label: "Runway Gen-3 Alpha", category: "text2video", vendor: "Runway", tag: "商用", family: "closed" },
  { value: "pika-3-t2v", label: "Pika 3 文生视频", category: "text2video", vendor: "Pika Labs", family: "closed" },
  { value: "happyhorse-t2v", label: "快乐马 HappyHorse 文生视频", category: "text2video", vendor: "Alibaba", tag: "低价", family: "closed" },
  { value: "wanxiang-2.7-t2v", label: "万相 2.7 文生视频 (开源)", category: "text2video", vendor: "Alibaba", tag: "开源旗舰", family: "open" },
  { value: "wanxiang-2.2-t2v", label: "万相 2.2 文生视频 (开源)", category: "text2video", vendor: "Alibaba", family: "open" },
  { value: "hunyuan-video-t2v", label: "HunyuanVideo 文生视频", category: "text2video", vendor: "Tencent", tag: "开源", family: "open" },
  { value: "cogvideox-5b", label: "CogVideoX-5B 文生视频", category: "text2video", vendor: "Zhipu", tag: "开源", family: "open" },
  { value: "ltx-2.3-t2v", label: "LTX 2.3 文生视频", category: "text2video", vendor: "Lightricks", tag: "开源·快", family: "open" },
  { value: "mochi-1", label: "Mochi 1 文生视频", category: "text2video", vendor: "Genmo", tag: "开源高质量", family: "open" },
  { value: "hunyuan-video-t2v-open", label: "HunyuanVideo T2V 开源", category: "text2video", vendor: "Tencent", family: "open" },
  { value: "fisheye-t2v", label: "Fisheye 文生视频 (开源)", category: "text2video", vendor: "开源", family: "open" },
  { value: "seedance-2-pro-i2v", label: "Seedance 2.0 Pro 图生视频", category: "img2video", vendor: "ByteDance", tag: "旗舰", family: "closed" },
  { value: "seedance-2-fast-i2v", label: "Seedance 2.0 Fast 图生视频", category: "img2video", vendor: "ByteDance", tag: "高清·快", family: "closed" },
  { value: "seedance-2-mini-i2v", label: "Seedance 2.0 Mini 图生视频", category: "img2video", vendor: "ByteDance", tag: "极速", family: "closed" },
  { value: "seedance-2-reference-i2v", label: "Seedance 2.0 全能参考视频", category: "img2video", vendor: "ByteDance", tag: "图+视频+音频", family: "closed" },
  { value: "veo-3-i2v", label: "Veo 3 图生视频", category: "img2video", vendor: "Google", tag: "高品质", family: "closed" },
  { value: "kling-2-i2v", label: "可灵 Kling 2 图生视频", category: "img2video", vendor: "Kuaishou", family: "closed" },
  { value: "minimax-hailuo-i2v", label: "MiniMax Hailuo 图生视频", category: "img2video", vendor: "MiniMax", family: "closed" },
  { value: "runway-gen-3-i2v", label: "Runway Gen-3 图生视频", category: "img2video", vendor: "Runway", family: "closed" },
  { value: "pika-3-i2v", label: "Pika 3 图生视频", category: "img2video", vendor: "Pika Labs", family: "closed" },
  { value: "happyhorse-i2v", label: "快乐马 HappyHorse 图生视频", category: "img2video", vendor: "Alibaba", tag: "低价", family: "closed" },
  { value: "wanxiang-2.7-i2v", label: "万相 2.7 图生视频 (开源)", category: "img2video", vendor: "Alibaba", tag: "开源旗舰", family: "open" },
  { value: "wanxiang-2.2-i2v", label: "万相 2.2 图生视频 (开源)", category: "img2video", vendor: "Alibaba", family: "open" },
  { value: "ltx-2.3-i2v", label: "LTX 2.3 图生视频", category: "img2video", vendor: "Lightricks", tag: "开源", family: "open" },
  { value: "cogvideox-i2v", label: "CogVideoX 图生视频", category: "img2video", vendor: "Zhipu", tag: "开源", family: "open" },
  { value: "hunyuan-video-i2v", label: "HunyuanVideo 图生视频", category: "img2video", vendor: "Tencent", tag: "开源", family: "open" },
];

export function getTargetModel(value: string): TargetModel | undefined {
  return TARGET_MODELS.find((model) => model.value === value);
}

export function getDownstreamModel(value: string): DownstreamModel | undefined {
  return DOWNSTREAM_MODELS.find((model) => model.value === value);
}

export function getDownstreamModels(category: Exclude<TaskCategory, "none">): DownstreamModel[] {
  return DOWNSTREAM_MODELS.filter((model) => model.category === category);
}
